#!/bin/bash
# Auto cache-bust: update ?v= query strings with current timestamp
STAMP=$(date +%s)
sed -i '' "s/style\.css?v=[^\"']*/style.css?v=$STAMP/g" index.html
sed -i '' "s/main\.js?v=[^\"']*/main.js?v=$STAMP/g" index.html
git add index.html
